/* Table: AGENCIA */
create table AGENCIA (
   ID_AGENCIA SERIAL not null,
   NOMBRE_AGENCIA VARCHAR(20) null,
   UBICACION_AGENCIA VARCHAR(20) null,
   constraint PK_AGENCIA primary key (ID_AGENCIA)
);

/* Table: CLIENTE */
create table CLIENTE (
   CEDULA_CLIENTE SERIAL not null,
   NOMBRES_CLIENTE VARCHAR(35) null,
   APELLIDOS_CLIENTE VARCHAR(35) null,
   TELEFONO_CLIENTE VARCHAR(10) null,
   DIRECCION_CLIENTE VARCHAR(50) null,
   CORREO_CLIENTE VARCHAR(30) null,
   constraint PK_CLIENTE primary key (CEDULA_CLIENTE)
);

/* Table: VEHICULO */
create table VEHICULO (
   ID_VEHICULO SERIAL not null,
   ID_AGENCIA INT4 null,
   TIPO_VEHICULO VARCHAR(40) null,
   IMAGEN_VEHICULO VARCHAR(100) null,
   KILOMETRAJE_VEHICULO VARCHAR(10) null,
   NOMBRE_VEHICULO VARCHAR(40) null,
   MODELO_VEHICULO VARCHAR(40) null,
   TRANSMISION_VEHICULO VARCHAR(40) null,
   RATING_VEHICULO NUMERIC null,
   DESCRIPCION_VEHICULO VARCHAR(100) null,
   PRECIO_VEHICULO NUMERIC null,
   DISPONIBILIDAD_VEHICULO BOOL null,
   constraint PK_VEHICULO primary key (ID_VEHICULO)
);

/* Table: ALQUILER */
create table ALQUILER (
   ID_ALQUILER SERIAL not null,
   ID_VEHICULO INT4 not null,
   CEDULA_CLIENTE INT4 not null,
   FECHA_INICIO_ALQ DATE not null,
   FECHA_FIN_ALQ DATE not null,
   constraint PK_ALQUILER primary key (ID_ALQUILER)
);

INSERT INTO AGENCIA (NOMBRE_AGENCIA, UBICACION_AGENCIA) VALUES ('Agencia Centro', 'Centro Ciudad');
INSERT INTO AGENCIA (NOMBRE_AGENCIA, UBICACION_AGENCIA) VALUES ('Agencia Norte', 'Zona Norte');
INSERT INTO AGENCIA (NOMBRE_AGENCIA, UBICACION_AGENCIA) VALUES ('Agencia Sur', 'Zona Sur');
INSERT INTO AGENCIA (NOMBRE_AGENCIA, UBICACION_AGENCIA) VALUES ('Agencia Este', 'Zona Este');
INSERT INTO AGENCIA (NOMBRE_AGENCIA, UBICACION_AGENCIA) VALUES ('Agencia Oeste', 'Zona Oeste');

INSERT INTO CLIENTE (NOMBRES_CLIENTE, APELLIDOS_CLIENTE, TELEFONO_CLIENTE, DIRECCION_CLIENTE, CORREO_CLIENTE) VALUES ('Laura', 'Estrada', '3123456789', 'Calle 70 #5-23', 'laura.est@example.com');
INSERT INTO CLIENTE (NOMBRES_CLIENTE, APELLIDOS_CLIENTE, TELEFONO_CLIENTE, DIRECCION_CLIENTE, CORREO_CLIENTE) VALUES ('David', 'Ramírez', '3009876543', 'Avenida Bolívar #12-48', 'david.ram@example.com');
INSERT INTO CLIENTE (NOMBRES_CLIENTE, APELLIDOS_CLIENTE, TELEFONO_CLIENTE, DIRECCION_CLIENTE, CORREO_CLIENTE) VALUES ('Sofía', 'Molina', '3201234567', 'Carrera 50 #34-56', 'sofia.mol@example.com');
INSERT INTO CLIENTE (NOMBRES_CLIENTE, APELLIDOS_CLIENTE, TELEFONO_CLIENTE, DIRECCION_CLIENTE, CORREO_CLIENTE) VALUES ('Juan', 'González', '3177654321', 'Diagonal 45 #67-89', 'juan.gonz@example.com');
INSERT INTO CLIENTE (NOMBRES_CLIENTE, APELLIDOS_CLIENTE, TELEFONO_CLIENTE, DIRECCION_CLIENTE, CORREO_CLIENTE) VALUES ('Carla', 'Fernández', '3189876543', 'Transversal 23 #98-76', 'carla.fern@example.com');

INSERT INTO ALQUILER (ID_VEHICULO, CEDULA_CLIENTE, FECHA_INICIO_ALQ, FECHA_FIN_ALQ) VALUES (1, 1, '2023-01-10', '2023-01-20');
INSERT INTO ALQUILER (ID_VEHICULO, CEDULA_CLIENTE, FECHA_INICIO_ALQ, FECHA_FIN_ALQ) VALUES (2, 2, '2023-02-15', '2023-02-25');
INSERT INTO ALQUILER (ID_VEHICULO, CEDULA_CLIENTE, FECHA_INICIO_ALQ, FECHA_FIN_ALQ) VALUES (3, 3, '2023-03-20', '2023-03-30');
INSERT INTO ALQUILER (ID_VEHICULO, CEDULA_CLIENTE, FECHA_INICIO_ALQ, FECHA_FIN_ALQ) VALUES (4, 4, '2023-04-05', '2023-04-15');
INSERT INTO ALQUILER (ID_VEHICULO, CEDULA_CLIENTE, FECHA_INICIO_ALQ, FECHA_FIN_ALQ) VALUES (5, 5, '2023-05-10', '2023-05-20');

INSERT INTO VEHICULO (ID_AGENCIA, TIPO_VEHICULO, IMAGEN_VEHICULO, KILOMETRAJE_VEHICULO, NOMBRE_VEHICULO, MODELO_VEHICULO, TRANSMISION_VEHICULO, RATING_VEHICULO, DESCRIPCION_VEHICULO, PRECIO_VEHICULO, DISPONIBILIDAD_VEHICULO) VALUES (1, 'Compacto', 'url_a_imagen_del_vehiculo1', '5000', 'Mazda 3', '2019', 'Manual', 4.8, 'Compacto ideal para la ciudad, económico en combustible.', 15000, TRUE);
INSERT INTO VEHICULO (ID_AGENCIA, TIPO_VEHICULO, IMAGEN_VEHICULO, KILOMETRAJE_VEHICULO, NOMBRE_VEHICULO, MODELO_VEHICULO, TRANSMISION_VEHICULO, RATING_VEHICULO, DESCRIPCION_VEHICULO, PRECIO_VEHICULO, DISPONIBILIDAD_VEHICULO) VALUES (2, 'Sedán', 'url_a_imagen_del_vehiculo2', '15000', 'Toyota Corolla', '2020', 'Automática', 4.5, 'Sedán cómodo y fiable, perfecto para cualquier viaje.', 18000, TRUE);
INSERT INTO VEHICULO (ID_AGENCIA, TIPO_VEHICULO, IMAGEN_VEHICULO, KILOMETRAJE_VEHICULO, NOMBRE_VEHICULO, MODELO_VEHICULO, TRANSMISION_VEHICULO, RATING_VEHICULO, DESCRIPCION_VEHICULO, PRECIO_VEHICULO, DISPONIBILIDAD_VEHICULO) VALUES (3, 'SUV', 'url_a_imagen_del_vehiculo3', '10000', 'Ford Escape', '2018', 'Automática', 4.7, 'Espacioso y cómodo, ideal para la familia.', 22000, TRUE);
INSERT INTO VEHICULO (ID_AGENCIA, TIPO_VEHICULO, IMAGEN_VEHICULO, KILOMETRAJE_VEHICULO, NOMBRE_VEHICULO, MODELO_VEHICULO, TRANSMISION_VEHICULO, RATING_VEHICULO, DESCRIPCION_VEHICULO, PRECIO_VEHICULO, DISPONIBILIDAD_VEHICULO) VALUES (4, 'Deportivo', 'url_a_imagen_del_vehiculo4', '8000', 'Chevrolet Camaro', '2020', 'Manual', 4.9, 'Potente y ágil, para los amantes de la velocidad.', 30000, TRUE);
INSERT INTO VEHICULO (ID_AGENCIA, TIPO_VEHICULO, IMAGEN_VEHICULO, KILOMETRAJE_VEHICULO, NOMBRE_VEHICULO, MODELO_VEHICULO, TRANSMISION_VEHICULO, RATING_VEHICULO, DESCRIPCION_VEHICULO, PRECIO_VEHICULO, DISPONIBILIDAD_VEHICULO) VALUES (5, 'Pickup', 'url_a_imagen_del_vehiculo5', '20000', 'Ford F-150', '2019', 'Automática', 4.6, 'Robusta y fiable para cualquier tarea o aventura.', 25000, TRUE);
